"""empty message

Revision ID: 388909ace18b
Revises: cf351258093c
Create Date: 2021-08-03 15:14:14.984398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388909ace18b'
down_revision = 'cf351258093c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
